function stoptimes146DWFAL = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STOPTIMES146DWFAL = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STOPTIMES146DWFAL = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  STOPTIMES146DWFAL = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  stoptimes146DWFAL = importfile("C:\Users\Maciej Kozłowski\Documents\Code\AutobusMZA\DANE\stoptimes_146_DW_FAL.xlsx", "stoptimes", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2026 20:11:40

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 8);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["stop_id", "stop_name", "stop_sequence", "arrival", "departure", "shape_dist_traveled", "stop_lat", "stop_lon"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["stop_id", "stop_name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["stop_id", "stop_name"], "EmptyFieldRule", "auto");

% Import the data
stoptimes146DWFAL = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    stoptimes146DWFAL = [stoptimes146DWFAL; tb]; %#ok<AGROW>
end

end