function MZA1 = importfile1(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  MZA1 = IMPORTFILE1(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  MZA1 = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  MZA1 = importfile1("C:\Users\Maciej Kozłowski\Documents\Code\AutobusMZA\DANE\MZA_1.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-May-2026 20:39:12

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2", "VarName3", "VarName4", "VarName5", "VarName6", "VarName7"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "datetime", "datetime"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName6", "InputFormat", "yyyy-MM-dd HH:mm:ss");
opts = setvaropts(opts, "VarName7", "InputFormat", "dd.MM.yyyy HH:mm:ss");
opts = setvaropts(opts, ["VarName4", "VarName5"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["VarName4", "VarName5"], "ThousandsSeparator", ",");

% Import the data
MZA1 = readtable(filename, opts);

end